### ISSUE TITLE
Docker Setup does not look easy as it sounds like

### ISSUE THREAD

**Issue by FurkanVG** [kouprlabs/voltaserve#113]
Hey,

I wanted to give this a shot and run it on my device, to be specfic run the docker stack via my portainer.

First i was confused to find the docker image, then i realized that this whole project is relying on 7! DIFFERENT docker containes from you and 5 other ones from third parties.
Now i see your docker-compose.yml, i could work with this and use it on Portainer, but is it not possible for you to atleast combine ur own 7 docker images to one?

I just think having 7 different images for one project is too complicated and is confusing people...

**Comment by bouassaba** [comment]
Hey,
The reason we have several containers is because it's a micro-services architecture, it allows scaling the software horizontally on clouds.
But, I totally understand your point, for a person who just wants to give it a shot, the Docker installation could be simplified further, I was thinking about this too.
Let me think about this more, to see if I can come up with some simplifications and I get back to you, I leave this GitHub issue open for this discussion.
In the meantime, let me know if I can assist you with the setup process until it's up and running for you.

**Comment by FurkanVG** [comment]
Hey,
thanks for the info!

Trying to make this run via Portainer, or in General, looks not that easy.

I copy pasted your docker-compose.yml and your .env and created my docker compose. Inital try failed cuz portainer realized a port is being used already. It was "VOLTASERVE_MINIO_CONSOLE_PORT" with "9001". Was used by my docker proxy, so I switched it to 9002 and it got created! I was able to access the web GUI fine under :3000, but when I tried to sign up, it always fails:

![image](https://github.com/kouprlabs/voltaserve/assets/68749298/d0a8a389-efc2-4f5b-a574-ffbd323b976d)


![image](https://github.com/kouprlabs/voltaserve/assets/68749298/f4cb2f98-8618-4e81-992d-a21f7b559b83)

Now this could be anything i think, so only sending one screenshot.

To go back to my docker images, its also interesting to see this:

![image](https://github.com/kouprlabs/voltaserve/assets/68749298/96cd2496-310e-4211-932b-d534d2eee37d)

Even after waiting for 15-30mins, some Docker Containers dont go into the "healthy" state. The docker container are all running, butb not healthy.

volt-api-1:
![image](https://github.com/kouprlabs/voltaserve/assets/68749298/37831be2-1874-42cb-a429-8cfb4eb54d87)

volt-idp-1:
![image](https://github.com/kouprlabs/voltaserve/assets/68749298/293ce74c-3c2f-4fc3-9ebe-37f87bc884b5)

![image](https://github.com/kouprlabs/voltaserve/assets/68749298/415b0329-ddb3-4838-89b3-a2d3d8e274bb)

Now im not gonna into detail to share all, but as last:

volt-mosaic-1:
![image](https://github.com/kouprlabs/voltaserve/assets/68749298/2bbb3169-35b0-4820-81db-b0d30ba50ba3)

Now funny enough is even that the URL shown here https://www.voltaserve.com/docs/api/errors/internal_server_error is not existing anymore :D 

Now i dont know if i did any mistakes, i am not a newbie, but i am not also a high expert. But trying to run this doesnt look that really easy i think. I can provide any logs if possible!

Thanks and GL

**Comment by bouassaba** [comment]
Thanks for the detailed description!

I would say just copying the docker-compose.yml and .env maybe not be enough.

Here are the steps to make it work in Portainer:

1) Clone the Git repository:
`git clone https://github.com/kouprlabs/voltaserve.git`

2) While inside the repository folder, do:
`docker-compose up -d`
This will download the containers automatically and start them.

3) Voltaserve can be seen now in the services section of Portainer.

4) Access the UI from your browser.

I suggest you delete everything you created including containers, images and volumes to start with a clean environment, follow the steps I wrote you and let me know how it went.

**Comment by FurkanVG** [comment]
Welp, i can confirm this worked flawlessly!

I still wonder why i couldnt create it directly through portainer. The health states are still reporting the same, but login etc all works!

**Comment by bouassaba** [comment]
Great to hear that it worked!
