### ISSUE TITLE
[UI/UX/API] Account sign up failure when password is not strong enough

### ISSUE THREAD

**Issue by cheney-yan-ifl** [kouprlabs/voltaserve#118]
While signing up a new account, and the password is not strong enough (for example, it does not contain a special character), sign up just fails with a general error. The response of account creation simply returns with 400 and a general error complaining password field has an issue, without specifying what the issue is.

What is expected
- UI can create in-place checking for the password rule for clearer indication.

**Comment by bouassaba** [comment]
@cheney-yan-ifl I agree, this feature is useful and needs to be implemented, I will work on it on the next update v2.1.
I will keep you updated on this, I will add this issue to the milestone.
