### ISSUE TITLE
Linting on Go code (golangci-lint)

### ISSUE THREAD

**Issue by dsonck92** [kouprlabs/voltaserve#130]
At work, we have a quite strict set of linting for our go projects utilizing `golangci-lint`. Now that we have more contributors, it might be nice to add this to this project to enforce a strict coding style.

A fair warning up front, though, is that the code will likely need quite a bit of changes to get it compliant to those standards. But in return I think we will get a lot of feedback on the validity and maintainability of the code. Personally I think it would be worth it, but it will definitely need some acceptance of the chores it brings.

I can try to add this to the projects and see how much its going to complain and what we want to tweak.

**Comment by bouassaba** [comment]
For sure, just add it ;)
I believe it will bring a lot of benefits.

**Comment by dsonck92** [comment]
Ah, I just noticed you already added the instructions for that (at least the api), but did not yet configure it very strictly. At work we enable all but a select few for reasons (deprecation or stylistic choices). I can borrow that and we can work from there. I think I will create an MR gradually enabling the linters to get a clear view on what each one adds and so we can follow the changes it brings.
