### ISSUE TITLE
New members in the org + Discord server

### ISSUE THREAD

**Issue by bouassaba** [kouprlabs/voltaserve#138]
Guys, there is no doubt that today we did an amazing job as a team, and I'm very thankful to your contributions, therefore it's with great  pleasure that I offer you to join the GitHub organization Kouprlabs as members, if you would like to, and I add you to Voltaserve repository as maintainers instead of just contributors, so you can review PRs from other contributors - this will make you feel that Voltaserve is yours too :)

This way you can also create new repositories that we might need in the organization, and to do more advanced DevOps workflows.

And of course, I can create a Discord server so we can chat in private if we need to.

I’ve said what I have to say :) It’s up to you now.

**Comment by dsonck92** [comment]
Yes, this sounds good, and the Discord is definitely a good idea, as I'm missing the slightly more direct communication. Although I admit that the comments do almost feel like a chat.

**Comment by loboda4450** [comment]
Guys, check your emails :)
