### ISSUE TITLE
PRs should push Docker images tagged with branch name instead of latest

### ISSUE THREAD

**Issue by bouassaba** [kouprlabs/voltaserve#142]
Right now, when we create a PR, GitHub Actions builds and pushes Docker images to the tag "latest" which ends up releasing unstable work in progress code to the users who rely on "latest" tag on Docker Hub.
We should change this, so when a PR is building, it pushes Docker images tagged with the branch name instead, and also think about removing this tag when the branch is merged, not to end up with many unused tags and reach some kind of limit of Docker Hub.

**Comment by loboda4450** [comment]
I think PRs should not push any docker image at all. It may build just to check if the build passes, but image push should be limited to push to main branch. That was the idea of splitting lint and build pipelines in the first place, but I had to be really in rush and should not contribute yesterday :D

**Comment by dsonck92** [comment]
Maybe, would it be possible to have it as a manually triggerable action on PRs to either a branch tag or hash tag? I agree that continuously pushing should not be necessary, and definitely not to `latest`, but sometimes I do want to have the convenience of just deploying a raw build in my cluster to test things out.

**Comment by bouassaba** [comment]
> Maybe, would it be possible to have it as a manually triggerable action on PRs to either a branch tag or hash tag? I agree that continuously pushing should not be necessary, and definitely not to `latest`, but sometimes I do want to have the convenience of just deploying a raw build in my cluster to test things out.

+1 for making it manually triggerable to a branch tag or hash tag, this will enable "feature environments" in a DevOps manner, and enable end-to-end testing for PRs before they land in main. This is the same what Vercel does with branch environments. I like the idea.

**Comment by loboda4450** [comment]
Yes, absolutely makes sense. But maybe it is better to tag it with last commit short sha? It provides even more precision while refering to existing error/bugs?

**Comment by dsonck92** [comment]
Yes, and technically it could prevent the need for a rebuild if the sha is equal again (e.g. dropping a commit)

**Comment by loboda4450** [comment]
I wonder whether tagging on push to main branch with "latest" is a good option or no. Shouldn't the releases be released only when a proper release/tag on github is created? (that sentence tho)

**Comment by dsonck92** [comment]
Well, I guess that pointing `latest` to the latest "released" version might be sensible. I imagine it's also interesting to re-tag to broader tags, i.e.: If we tag 2.3.1, we also push to 2.3, 2 and latest.

And probably also just directly decide *not* to support back porting. Otherwise we get ambiguities if we deliver 3.0.0 which is completely different, but then bugfix 2.3.2 afterwards due to a critical change, because people need to opt-in to upgrade to 3.0.0

**Comment by loboda4450** [comment]
Yes, that's the thing I skipped in tagging. About rejecting backporting, how would you like to achieve that? Just by assuming that we aint gonna do that or by some other means?

**Comment by dsonck92** [comment]
Yeah, probably that. Just never start using release branches that allow them. We do support back-porting at work, through release branches, and it can be powerful, but it also stops the desire to update. We should make sure the latest and greates is, the latest and greatest. And if there's a deviation people don't like, it might make sense to fork.

**Comment by loboda4450** [comment]
Speaking of versioning I opt for keeping semver model, which will reflect in getting rid of this annoying "v" in front of each tag. It will also have a impact in development, as semver requires certain levels of compatibility between patch, minor and major.
Refer to https://semver.org/

CC: @bouassaba

**Comment by dsonck92** [comment]
Keep in mind that the go code has specific conventions regarding this. Also, I just realized we completely screwed up this part by doing v2 already. The go libraries require the `v` prefix in the tags to be present. But do remove them from the docker images.
