### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by loboda4450** [kouprlabs/voltaserve#151]
As in nextcloud I'd really appreciate a admin dashboard/panel with e.g. summing up users, their managable quota, maybe some kind of RBAC management.

**Comment by dsonck92** [comment]
Yes, also a general overview of the organizations/workspaces structure would be beneficial to have. Probably also having 2 rules to get access: those you are owner of or if you are site admin

**Comment by hoangna1204** [comment]
Hi I would like to ask if the Admin Dashboard offers the possibility to select which region/location to create S3 bucket?

**Comment by dsonck92** [comment]
@hoangna1204 The future plans regarding S3 would probably be to allow setting the bucket creation parameters per company. I do think this would fit the admin portal scope. However, I'm also looking forward to the ability to have the bucket specified when the workspace is created (if auto creation has been disabled) to allow reuse of existing buckets, or in situations where bucket creation does not fall under Voltaserve responsibilities.

**Comment by hoangna1204** [comment]
@dsonck92 Agreed on that. Leaving the S3 creation for clients would be better as it gives users control over there data storage.
