### ISSUE TITLE
Failure to attach snapshot to file

### ISSUE THREAD

**Issue by dsonck92** [kouprlabs/voltaserve#256]
### **Pre-checklist:**

- [ ] I have searched for similar issues in the repository and could not find a duplicate.
- [ ] I have provided detailed steps to reproduce the bug.
- [ ] I have included all necessary information about my environment.

### **Summary:**

_A brief summary of the bug._

---

### **Steps to Reproduce:**

1. _Step 1 description_
2. _Step 2 description_
3. _Step 3 description_

**Expected Result:**

_Description of what you expected to happen._

**Actual Result:**

_Description of what actually happened._

**Screenshots or Code Snippets (if applicable):**

```
2024/08/08 12:06:03 /build/repo/file_repo.go:408 ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT): "sql txn" meta={id=53fd641c key=/Table/139/12/"d7YyJ2QaVenYJ"/0 iso=Serializable pri=0.00891704 epo=0 ts=1723118750.959084010,2 min=1723118750.644581883,0 seq=1} lock=true stat=PENDING rts=1723118750.644581883,0 wto=false gul=1723118751.144581883,0 (SQLSTATE 40001)
[12974.037ms] [rows:1] UPDATE "file" SET "workspace_id"='3X9EPygWN4PkD',"name"='1491-colour.png',"type"='file',"parent_id"='r7RPWDjonoLkX',"snapshot_id"='LBeAoKk2QNMzJ',"create_time"='2024-08-08T12:05:40Z',"update_time"='2024-08-08T12:05:50Z' WHERE "id" = 'd7YyJ2QaVenYJ'
2024-08-08T12:06:03.701Z        ERROR   ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT): "sql txn" meta={id=53fd641c key=/Table/139/12/"d7YyJ2QaVenYJ"/0 iso=Serializable pri=0.00891704 epo=0 ts=1723118750.959084010,2 min=1723118750.644581883,0 seq=1} lock=true stat=PENDING rts=1723118750.644581883,0 wto=false gul=1723118751.144581883,0 (SQLSTATE 40001)
github.com/kouprlabs/voltaserve/api/errorpkg.ErrorHandler
        /build/errorpkg/error_handler.go:28
github.com/gofiber/fiber/v2.(*App).ErrorHandler
        /go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.5/app.go:1063
github.com/gofiber/fiber/v2.(*App).handler
        /go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.5/router.go:174
github.com/valyala/fasthttp.(*Server).serveConn
        /go/pkg/mod/github.com/valyala/fasthttp@v1.55.0/server.go:2379
github.com/valyala/fasthttp.(*workerPool).workerFunc
        /go/pkg/mod/github.com/valyala/fasthttp@v1.55.0/workerpool.go:224
github.com/valyala/fasthttp.(*workerPool).getCh.func1
        /go/pkg/mod/github.com/valyala/fasthttp@v1.55.0/workerpool.go:196
```
_Add any screenshots or code snippets that might help in diagnosing the issue._

---

### **Environment Details:**
**Deployment type**
- [ ] Docker
- [ ] Kubernetes
- [ ] Other

_Any relevant to the case environment details (e.g. browser in case of UI bug)_ 

---

### **Additional Information:**

_Any additional information, context, or logs that might be relevant to the issue._

---

[//]: # (**Thank you for helping us improve our project!**)

**Comment by dsonck92** [comment]
I will have to digest this a bit more, but I wanted to document this event

**Comment by bouassaba** [comment]
I tested this, works fine on my side.
@dsonck92 can you reproduce this?

**Comment by bouassaba** [comment]
@dsonck92 is this still an issue?

**Comment by dsonck92** [comment]
I haven't seen this recently no, so for now I'll close it till it pops up again
