### ISSUE TITLE
Upload folder (recursively)

### ISSUE THREAD

**Issue by stnokott** [kouprlabs/voltaserve#71]
Will there be the possibility to upload whole folders recursively?

Currently, the "Upload file" button doesn't allow selecting folders and drag-n-dropping folders onto the web UI also doesn't work (the browser itself will just simply open the folder contents).

This would be great to reduce the tediousness of uploading big batches of files, nested in multiple folders.

---

And thanks for this piece of software, looks promising and might become a true alternative to the established tools for self-hosted cloud storage.

**Comment by eliasby** [comment]
Totally agree, this feature is critical for productivity. I had it planned for quite sometime already but I never had the chance to work on it.
Currently, the only way to achieve it is with a WebDAV client.
I will try to work on this in the next few days. I will post updates on my progress here.

**Comment by eliasby** [comment]
@stnokott the feature is now implemented and merged in the main branch.
Let me know if that fulfills your requirements, and feel free to reopen this issue in case.

**Comment by eliasby** [comment]
I forgot to mention that a folder can be uploaded recursively with drag and drop, and not via the "Upload File" button.

**Comment by stnokott** [comment]
Looks good!

Thanks for the continuous work!

Currently, this only works for small datasets though, uploading huge folders (~50k files total, multiple levels of nesting) results in the website becoming unresponsive on my end.
I'm not very experienced with webdevelopment, but I suspect, this might be a general problem with drag & drop functionality in websites.
Adding a dedicated "Upload folder" button might be worth looking into.

To underline this need a bit more: currently, I have a self-hosted cloud storage with multiple millions of files. Migrating that library over to Voltaserve would currently be a big pain as I would need to select small subsets of files at a time, uploading them in small increments to Voltaserve.
The ability to upload bigger batches at once would ease that pain a lot.

**Comment by eliasby** [comment]
Thanks for the feedback!
Totally makes sense, I just implemented the upload folder functionality, I tried to keep the UI clean by keeping one button "Upload" that opens a dropdown which lets you choose whether you want to upload files or a folder.
Let me know if that works well for your use-case, especially from the performance aspect.

**Comment by stnokott** [comment]
Wow, thanks for the quick implementation and sorry for the late reply!

Unfortunately, the symptom when using the dedicated "Upload Folder" button is the same.
I opened a new issue (!80) for that since it's out of scope for this issue.
