### ISSUE TITLE
Website becomes unresponsive when uploading huge folder

### ISSUE THREAD

**Issue by stnokott** [kouprlabs/voltaserve#80]
When uploading a huge folder (~56k items), the website becomes entirely unresponsive.
I waited around 30mins, but nothing visibly changed.

The upload process doesn't seem to start either since no items are actually uploaded when eventually reloading the page.

There's nothing in the DevTools console either, so let me know if I can provide you with any information for help regarding resolving this!

**Comment by bouassaba** [comment]
@stnokott we did a lot of performance optimization on the the new v2 release, could you please try it and let me know if this improves?

**Comment by bouassaba** [comment]
I will close this issue for now, feel free to reopen it if the issue persists.

**Comment by stnokott** [comment]
I am currently moving, so my NAS is offline until we're done unpacking things.
Will check back in once it's back online. Thanks for your hard work!

**Comment by stnokott** [comment]
Right, sorry for the long wait time.

So I can confirm that uploading a large dataset works fine now, **the problem this issue was created for is thus fixed**.

I feel there is still some potential for optimization since my folder with 1.079 files totalling ~80MB took around 3s per image upload which is a lot, even for slow HDDs (which my NAS is running on).
