### ISSUE TITLE
voltaserve-api unhealthy 

### ISSUE THREAD

**Issue by ImShallo** [kouprlabs/voltaserve#82]
Hi, I tried to install Voltaserve on Portainer on my linux machine, but I have this problem: the voltaserve-api container seems to be not working, so I can't even sign up because I don't get the confirmation email. On the Portainer panel it appears as "unhealthy"

Log of voltaserve-api container:
```

 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.46.0                   │ 
 │               http://127.0.0.1:5000               │ 
 │       (bound on host 0.0.0.0 and port 5000)       │ 
 │                                                   │ 
 │ Handlers ............ 87  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................. 1 │ 
 └───────────────────────────────────────────────────┘ 
```

And when I try to access localhost:5000 this appears: `Missing or malformed JWT`

**Comment by eliasby** [comment]
@ImShallo could you please update your main branch to the latest commit, recreate all containers, by doing `docker compose down -v` (caution': this will deleted volumes and you will lose data) then `docker compose up -d` and confirm if the issue still exits?

**Comment by bouassaba** [comment]
@ImShallo let me know it this is fixed on your side, if not we can reopen this issue.
I will close it for now.
