### ISSUE TITLE
Setup not working correctly

### ISSUE THREAD

**Issue by Joly0** [kouprlabs/voltaserve#84]
Hey, i just pulled your github repo and run `docker compose build` and `docker compose up -d` as per the documentation (had to change 3 ports, because they were already taken). I opened up the sign-up page and created an account, but i couldnt sign in with these credentials. I also opened mailcatcher as per the documentation, but there is nothing. No mail. The page loads normally, i can see and click various buttons, but nothing else.

**Comment by eliasby** [comment]
Hey, thanks, there have been some bugs on the Identity Provider (idp), that's most likely the reason why you go this issue, I'm working on this now, and I will give an update here soon.

**Comment by eliasby** [comment]
@Joly0 could you please update your main branch to the latest commit and confirm if the issue still exists? Thanks.

**Comment by bouassaba** [comment]
@Joly0 I will close this for now, if the issue still persist, let's reopen this issue, I will close it for now.
